% Input: 
% - coeffs: PCE coefficients (vector) [u]
% - indices: Multi-index (matrix), where rows correspond to basis functions [IDH]
% - d: Number of input variables
% - e.g.: [eps_r lambda]
% Example PCE coefficients and indices
coeffs = [    8.5865;...
    0.3625;...
   -0.2179;...
   -0.2226;...
    0.1934;...
   -2.0791;...
    0.0295;...
    0.0724;...
   -0.1211;...
    0.0606;...
    0.0165;...
   -0.0881;...
    0.1687;...
   -0.3072;...
    1.2405;...
   -0.0015;...
    0.0145;...
   -0.0319;...
    0.1913;...
   -0.0374;...
   -0.4752]'; % Example coefficients
indices = [     0	0;...
1	0;...
0	1;...
2	0;...
1	1;...
0	2;...
3	0;...
2	1;...
1	2;...
0	3;...
4	0;...
3	1;...
2	2;...
1	3;...
0	4;...
5	0;...
4	1;...
3	2;...
2	3;...
1	4;...
0	5]; % Corresponding multi-indices
d = size(indices,2); % Number of input variables


% Compute Sobol indices
[S, ST] = sobol_indices_pce(coeffs, indices, d);

% Display results
disp('First-order Sobol indices:');
disp(S);
disp('Total-order Sobol indices:');
disp(ST);

function [S, ST] = sobol_indices_pce(coeffs, indices, d)
    % Total variance
    total_variance = sum(coeffs(2:end).^2); % Exclude the constant term (c_0)
    
    % Initialize Sobol indices
    S = zeros(1, d);   % First-order indices
    ST = zeros(1, d);  % Total-order indices
    
    % Loop through each variable
    for i = 1:d
        % First-order terms: only variable i appears (other indices are 0)
        first_order_mask = (indices(:,i) > 0) & all(indices(:,[1:i-1, i+1:end]) == 0, 2);
        S(i) = sum(coeffs(first_order_mask).^2) / total_variance;
        
        % Total-order terms: variable i appears (ignore other indices)
        total_order_mask = indices(:,i) > 0;
        ST(i) = sum(coeffs(total_order_mask).^2) / total_variance;
    end
end


